spring:
  application:
    name: alpjom-api
  jackson:
    time-zone: Asia/Taipei
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}?serverTimezone=Asia/Taipei
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart: # 可以在這邊系統級設定大一點，再到 Service 層限制更小
      max-file-size: 50MB # 單個檔案上限：預設 1MB
      max-request-size: 100MB # 單次請求上限：預設 10MB


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  開發時印出 SQL


jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}


server:
  port: 8080
  address: 0.0.0.0
  forward-headers-strategy: framework
  # 讓 Spring 讀取 Nginx 附加的 X-Forwarded-* Header，
  # 正確識別原始請求是 https、取得訪客真實 IP（而非 Nginx 內部位址）

r2:
  endpoint: ${R2_END_POINT}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket-name: ${R2_BUCKET_NAME}
  public-url: ${R2_PUBLIC_URL}